version: "3"

services:
  donkey-editor:
    image: ${DOCKER_REGISTRY}donkey-editor
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./models:/app/src/mycar/models
      - ./data:/app/src/mycar/data
    ports:
      - 8888:8888